# Fase 1: Data Ingestion & Cleaning
## Sistema de Predicción de Demanda Turística y Precios Dinámicos

En este cuaderno realizamos la extracción, limpieza y consolidación de las tres fuentes oficiales del MINCETUR (sitios turísticos, turismo emisivo y turismo receptivo) junto a la serie climatológica histórica obtenida vía API REST de Open-Meteo.

In [1]:
# Cargamos las librerías principales del entorno
import os
import sys
import pandas as pd

# Añadimos la carpeta 'src' al path para poder importar nuestros módulos locales
sys.path.append(os.path.abspath('../src'))
from utils_climate import obtener_clima_historico
from ingestion import ejecutar_pipeline_ingestion

print("Librerías e infraestructura cargadas correctamente.")

Librerías e infraestructura cargadas correctamente.

### 1. Ejecución del Pipeline Automatizado de Ingestión

In [2]:
# Ejecutamos el pipeline completo definido en src/ingestion.py
df_consolidado = ejecutar_pipeline_ingestion()
df_consolidado.head(10)

=== INICIANDO FASE 1: INGESTION Y LIMPIEZA DE DATOS ===
Procesando datasets del MINCETUR...

Consultando clima histórico desde API Open-Meteo...

¡Éxito! Dataset consolidado generado correctamente en:
 -> C:\Users\ADMIN\tourism-demand-forecasting\data\processed\datos_consolidados_limpios.csv
 -> Filas totales: 84 (84 meses de Enero 2019 a Diciembre 2025)

,fecha,ANIO,ID_MES,demanda_total,visitantes_sitios_total,turistas_receptivo_total,turistas_emisivo_total,temp_mean,temp_max,temp_min,precipitacion
0,2019-01-01,2019,1,2224275.0,1848012.0,376263,309861.0,11.80,18.389999,4.79,190.899994
1,2019-02-01,2019,2,1934306.0,1582765.0,351541,287472.0,11.64,18.340000,6.49,240.300003
2,2019-03-01,2019,3,1735683.0,1360879.0,374804,267095.0,11.90,18.290001,6.24,111.599998
3,2019-04-01,2019,4,2053211.0,1692320.0,360891,250515.0,11.77,18.240000,6.24,68.000000
4,2019-05-01,2019,5,1945199.0,1585162.0,360037,267444.0,11.36,19.290001,3.79,22.200001
5,2019-06-01,2019,6,2062426.0,1708820.0,353606,245351.0,10.94,19.090000,2.04,7.400000
6,2019-07-01,2019,7,2626772.0,2214357.0,412415,301343.0,10.48,20.940001,1.29,16.600000
7,2019-08-01,2019,8,2627483.0,2245912.0,381571,288591.0,10.98,20.340000,2.59,16.200001
8,2019-09-01,2019,9,2165907.0,1816812.0,349095,262530.0,11.63,22.940001,3.74,23.900000
9,2019-10-01,2019,10,2227940.0,1882504.0,345436,281093.0,12.31,20.990000,5.64,62.200001

### 2. Inspección y Resumen Estadístico del Dataset Consolidado

In [3]:
# Revisamos la información general de tipos de datos y nulos
df_consolidado.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   fecha                     84 non-null     datetime64[us]
 1   ANIO                      84 non-null     int64
 2   ID_MES                    84 non-null     int64
 3   demanda_total             84 non-null     float64
 4   visitantes_sitios_total   84 non-null     float64
 5   turistas_receptivo_total  84 non-null     int64
 6   turistas_emisivo_total    84 non-null     float64
 7   temp_mean                 84 non-null     float32
 8   temp_max                  84 non-null     float32
 9   temp_min                  84 non-null     float32
 10  precipitacion             84 non-null     float32
dtypes: datetime64[us](1), float32(4), float64(3), int64(3)
memory usage: 6.0 KB

In [4]:
# Mostramos el resumen estadístico de las variables consolidadas
df_consolidado.describe()

,fecha,ANIO,ID_MES,demanda_total,visitantes_sitios_total,turistas_receptivo_total,turistas_emisivo_total,temp_mean,temp_max,temp_min,precipitacion
count,84,84.000000,84.000000,8.400000e+01,8.400000e+01,84.000000,84.000000,84.000000,84.000000,84.000000,84.000000
mean,2022-06-16 14:17:08.571428,2022.000000,6.500000,1.451351e+06,1.249926e+06,201425.369048,194573.476190,11.661428,20.134048,4.330476,98.540466
min,2019-01-01 00:00:00,2019.000000,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,10.020000,17.190001,-0.510000,2.600000
25%,2020-09-23 12:00:00,2020.000000,3.750000,1.022480e+06,9.307018e+05,72461.250000,87837.500000,11.117500,18.727500,3.377500,23.250000
50%,2022-06-16 00:00:00,2022.000000,6.500000,1.654340e+06,1.392996e+06,234974.000000,243281.500000,11.635000,20.165000,4.390000,73.500000
75%,2024-03-08 18:00:00,2024.000000,9.250000,1.977430e+06,1.691062e+06,284805.500000,274369.500000,12.172500,21.152500,5.602500,177.950001
max,2025-12-01 00:00:00,2025.000000,12.000000,2.627483e+06,2.245912e+06,412415.000000,320525.000000,13.300000,23.540001,7.790000,298.399994
std,NaN,2.012012,3.472786,7.337691e+05,6.227704e+05,124381.423611,106303.429235,0.735683,1.576358,1.768899,83.758186

### 3. Conclusión de la Fase 1
Se ha generado exitosamente el archivo `data/processed/datos_consolidados_limpios.csv` con **84 registros mensuales** (Enero 2019 a Diciembre 2025). El dataset se encuentra 100% validado y listo para ser entregado a la **Fase 2: Exploratory Data Analysis (EDA)**.